### ISSUE TITLE
Add derived query to find books by title

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#10]
Add a derived query to find by book title (case insensitive). This will also need to be added to the query resolver

Accompanying tests will be required.

**Comment by nikole24** [comment]
Hello! Can I take this task?

**Comment by knjk04** [comment]
Hello, sure. I'll assign you to it. Feel free to reach out to us by creating a new discussion on GitHub or on Slack if you need help

**Comment by nikole24** [comment]
@knjk04  i am trying to build the project but  i get this: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/karankumar/booksapi/BooksApiApplication has been compiled by a more recent version of the Ja
va Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
my java version is 11 i have checked it out. Can you help me please, do you know what i have to do?

**Comment by nikole24** [comment]
i have done the code i had to changed btw

**Comment by knjk04** [comment]
Could you please paste the stack trace into a GitHub Gist, Pastebin or something equivalent and then share it?

Also, 
- what JDK version (I know you said 11, but what's the minor and patch version) and type (e.g. Oracle, OpenJDK) are you using?
- what OS are you suing?

**Comment by nikole24** [comment]
11.0.4  Oracle
and I work on windows 10
I am going to keep searching for a solution.

**Comment by nikole24** [comment]
I resolved the issue as following : I add the maven-compiler-plugin in the pom. xml with configuration java version 11.
