### ISSUE TITLE
 Add derived query to find books by genre

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#11]
Add a derived query to find by book genre (using our enum). This will also need to be added to the query resolver.

Accompanying tests will be required.

**Comment by shivansh29** [comment]
Hey is this issue avai;able can you assign io to me

**Comment by knjk04** [comment]
@shivansh29 Sure, thanks!

**Comment by shivansh29** [comment]
BookRepositry   -  `@Query("FROM Book where title = :booktitle")`
                             ` Book findByTitle(@Param("booktitle") String title);`
QueryResolver  -  `public Book findByTitle(String title) {
    	                     return bookRepository.findByTitle(title);  }`

These are the changes I made  
Let me know if there is something wrong or if it is not following any kinds of standards 
It is going to be my first contribution

**Comment by knjk04** [comment]
@shivansh29 Sorry, I didn't see this before. I'll review your pull request. Thanks

**Comment by lubomirdruga** [comment]
Hi @knjk04, is this issue available? I would like to help with that :)

**Comment by knjk04** [comment]
Hi @lubomirdruga, it's still available. I'll assign you to it. Thanks!

**Comment by lubomirdruga** [comment]
> Add a derived query to find by book title (using our enum). This will also need to be added to the query resolver.
> 
> Accompanying tests will be required.

Hey @knjk04 
Do you mean by this issue to find books by **genre** or **title?** Because the issue name and your description does not match(I guess it's a typo).

**Comment by knjk04** [comment]
Hi @lubomirdruga, my bad. Good spot. I meant genre, I've fixed the description now. Thanks!
