### ISSUE TITLE
Add derived query to find books by author

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#12]
Add a derived query to find by Author (using the `Author` type). This will also need to be added to the query resolver

Accompanying tests will be required.

**Comment by nikole24** [comment]
Hello! Can I work on this task too?

**Comment by kev711** [comment]
Can I work on this ?
I will need to know what is meant by "using the Author type" since a `findByAuthor()` method is already available in `om.karankumar.booksapi.repository.BookRepository`.

**Comment by knjk04** [comment]
My bad, it looks like this was completed recently. I should have closed this issue. Thanks for expressing an interest in this, though!
