### ISSUE TITLE
Exclude certain files from JaCoCo reports

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#122]
We don't want the test coverage to include:
- BooksApiApplication.java
- Any class in the `model` package

**Comment by Wildschut** [comment]
Hi, can I be assigned this issue?

**Comment by knjk04** [comment]
Hi, sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@Wildschut For some reason, SonarCloud is not ignoring these: https://sonarcloud.io/component_measures?id=Project-Books_books-api&metric=coverage&view=list

**Comment by Wildschut** [comment]
Hi Karan, 

I'm not sure how to interpret the results of the https://sonarcloud.io/dashboard?id=Project-Books_books-api&pullRequest=138.

I think its only analyzing the changed pom?

How can I verify the changes made are the intended result? Tried setting up my own sonarqube but I don't have enough know how right now to do it timeously.

**Comment by knjk04** [comment]
Something seems to be going wrong with Sonar because it's now pointing to the Book Project. I'll re-close this issue and investigate further on my end. Thanks!
