### ISSUE TITLE
Return URL for book covers in response

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#131]
Example of one of our covers: https://bapiimagesdev.blob.core.windows.net/covers/1/small.jpg

The prefix will always be https://bapiimagesdev.blob.core.windows.net/covers/. The 1 refers to a unique ID that refers to that specific book. The file name can either be called 'small', 'medium' or 'large', followed by an extension type (currently, we only accept .jpg and .png ).

A book can have many covers: https://github.com/Project-Books/books-api/blob/main/src/main/java/com/karankumar/booksapi/model/Book.java#L105.

This method https://github.com/Project-Books/books-api/blob/main/src/main/java/com/karankumar/booksapi/model/cover/Cover.java#L75 returns the full URL to an image.

In methods like `getPathToSmall()`, we construct the full URL: https://github.com/Project-Books/books-api/blob/main/src/main/java/com/karankumar/booksapi/model/cover/Cover.java#L75. We need to return this for the `smallFileType`, `mediumFileType` and `largeFileType`

**Comment by knjk04** [comment]
@jhanna60

**Comment by jhanna60** [comment]
Happy to pick this up @knjk04
