### ISSUE TITLE
Dockerise backend

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#134]
We should dockerise the backend to make it easier for people, particularly our frontend developers, to get this running without needing to set things up (e.g. install the JDK, etc.). It should also start and run our PostgreSQL database.

Use a minimal Alpine distribution to run the Spring app.

For our development environment, we can use the preset Postgres credentials (username, password, host, etc.).

**Comment by knjk04** [comment]
@Wildschut Could you reply that you're interested in picking this up so that your name appears in the assignees list for me to assign this to you?

**Comment by Wildschut** [comment]
Hi, yes I'd interested.
