### ISSUE TITLE
Make the blurb field required

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#14]
Make the `blurb` field required in the `Book` entity and schema

**Comment by navneet35** [comment]
@knjk04 : Please assign this issue to me.

**Comment by knjk04** [comment]
@navneet35 Sure, I'll assign you to the issue. Thanks!

**Comment by knjk04** [comment]
@navneet35 How are you getting on with this issue? If you need any help on this, feel free to reach out to us on Slack

If you need more time, that's fine, but please let us know.

**Comment by navneet35** [comment]
@knjk04 : Apologize for the delay. I was occupied with something. I will complete it soon. Thanks!

**Comment by navneet35** [comment]
@knjk04 
Please find the approach I am considering:
There will be 2 changes to make the blurb field required:
1. add '!' operator in books.graphqls([link](https://github.com/Project-Books/books-api/blob/20d71f9c0cf90a17bd3628dfec3711366d92479c/src/main/resources/graphql/book.graphqls#L6)).
2. Add @NotEmpty annotation on blurb field in Book.java([link](https://github.com/Project-Books/books-api/blob/c83fdc70a2d5292b607280fac56692001d701819/src/main/java/com/karankumar/booksapi/model/Book.java#L56))

Let me know you have any inputs.

**Comment by knjk04** [comment]
@navneet35 That sounds good, thanks
