### ISSUE TITLE
Change findByTitleIgnoreCase to return an array

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#144]
Change findByTitleIgnoreCase to return an array of books, not just one (see thread: https://github.com/Project-Books/book-project/issues/882). We will also need to have multiple books with the same name so we can properly test this functionality.

**Comment by YashxAnand** [comment]
Hi knjk04, I would like to work on this issue.

**Comment by knjk04** [comment]
Hi @YashxAnand. apologies for the delay in getting back to you. This issue is already assigned, but feel free to request to be assigned to one of our other, non-assigned issues
