### ISSUE TITLE
Add literary awards won

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#15]
Add a literary award won entity

Fields:
- Unique ID
- An enum to represent the name of the literary award:
   - Women's Prize for Fiction
   - Orwell Book Prize
   - The Portico Prize
   - The Baillie Gifford Prize for Non-Fiction
   - International Dylan Thomas Prize
   - The Man Booker Prize
   - The Man Booker International Prize
   - Nobel Prize in Literature
- Category (nullable string)
- Year (int)

It should be possible to search for all of the award winners of a literary award (we could use a derived query here).

**Comment by mparkersimms** [comment]
I'd like to work on this issue if that's alright with you?

**Comment by knjk04** [comment]
Thanks for your interest in this! We only assign at most issue at a time for new contributors (see https://project-books.github.io/docs/contributing/#new-contributors-assigned-to-at-most-one-issue-at-a-time), but we'd be happy to assign you to this if it's still available after we've merged in a pull request for your currently assigned issue

**Comment by swetharnaik** [comment]
@knjk04 Could I work on this issue?

**Comment by knjk04** [comment]
@swetharnaik Sure, thanks a lot! I've updated the issue description

**Comment by swetharnaik** [comment]
@knjk04 Have added Award entity. Please check output below. If all is good, will raise a PR.
![image](https://user-images.githubusercontent.com/17508164/124376670-be0b1f00-dcc5-11eb-9b6e-2662b715d63a.png)

**Comment by knjk04** [comment]
@swetharnaik Thanks, this looks good! Would it be possible to remove 'IgnoreCase' from the method name and trim the input award name for leading or trailing whitespace if you haven't done so already?

**Comment by swetharnaik** [comment]
@knjk04 Sure
