### ISSUE TITLE
Add language to schema

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#18]
Add a `language` field to the `Book` schema and entity. This should be represented by an enum and should be a mandatory field.

For now, the following languages should be added (it needs to be kept in this alphabetical order)

```
Afrikaans
Albanian
Arabic
Armenian
Bengali
Bulgarian
Chinese
Czech
Danish
Dutch
English
Estonian
Finnish
French
German
Greek
Gujarati
Italian
Hawaiian
Hebrew
Hindi
Japanese
Korean
Latin
Polish
Portuguese
Punjabi
Russian
Sanskrit
Serbian
Sindhi
Spanish
Swahili
Swedish
Tamil
Telegu
Thai
Turkish
Urdu
Welsh
```

**Comment by chetanchilhate** [comment]
I could work on this.  Do you need a constructor similar to BookFormat?

**Comment by knjk04** [comment]
@chetanchilhate Sure, I'll assign you to the issue. Thanks! Feel free to reach to us on Slack should you need anything

> Do you need a constructor similar to BookFormat?

Yes, please

**Comment by chetanchilhate** [comment]
@knjk04 in constructor you want keep the full name or just initials for the language like **en** for English

**Comment by knjk04** [comment]
@chetanchilhate Let's keep the full name

**Comment by chetanchilhate** [comment]
@knjk04 I am not able to join slack channel it says the link is no longer active
 
i am getting this output is this expected 

![image](https://user-images.githubusercontent.com/10488480/99898498-c202a780-2cc7-11eb-9dee-3e2f9c7f9e8d.png)

**Comment by knjk04** [comment]
My bad, here's an updated link: https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg

No, there could be an error on the server (backend) because it shouldn't say the 'server cannot be reached'. Are you getting an error in your IDE/terminal? Feel free to ask on the #help channel on Slack, so that we can help with this

**Comment by chetanchilhate** [comment]
@knjk04  i have commented maxQueryDepth and no longer getting 'server can not be reached' issue.  Also i am not getting any error in IDE as well

![image](https://user-images.githubusercontent.com/10488480/99902270-8a552900-2ce2-11eb-91cb-a1bf8df2a022.png)

![image](https://user-images.githubusercontent.com/10488480/99902286-ab1d7e80-2ce2-11eb-92f2-7b20a0741021.png)

**Comment by knjk04** [comment]
@chetanchilhate Could you create a PR for this so that I can take a look?

**Comment by chetanchilhate** [comment]
sure

**Comment by knjk04** [comment]
![image](https://user-images.githubusercontent.com/11173328/99999910-c064dc80-2db8-11eb-96c9-cd3842793098.png)

You're right, the max query depth was exceeded. That's fine, though. I'll create a new issue for that to determine a better threshold
