### ISSUE TITLE
Add book in author schema

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#28]
`#    books: [Book!]! TODO: bring this back`

In the `Author` schema, uncomment the `books` line and get it to work. It should be possible to find all of the books that belong to a particular author

**Comment by nikole24** [comment]
Hello! Can I work on this task too?

**Comment by knjk04** [comment]
Hello, sure. Thanks!

**Comment by nikole24** [comment]
I have a question before I start working on this. For returning the books of an author can I use the findAllAuthors method that already exists or I should create a new method that will have inputs the first name and last name of the author and return only the book list of that author?

**Comment by knjk04** [comment]
I don't think you'll need that method. You may want a `findByAuthor` method in the `BookRepository`, though
