### ISSUE TITLE
Host is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#54]
**Describe the bug**
Unable to connect to the MySQL

**To Reproduce**
1. Go to `localhost:8082`
2. Enter in `root` for the username and `rootpassword` for the password
3. See error

**Expected behavior**
A user should be able to log in without needing to configure anything else.

**Screenshots**
![image](https://user-images.githubusercontent.com/11173328/108958240-9ac2ca00-766a-11eb-806c-b052907657d9.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
This may be a permissions-related issue.

**Comment by kev711** [comment]
Not sure about the docker image config, but MySQL in default config allows only `localhost` to connect. Maybe that's why docker IP `172.25.0.2` isn't allowed to connect.

**Comment by knjk04** [comment]
That's strange. This works for me on Linux. I thought this was set to run on `localhost`?

**Comment by kev711** [comment]
`localhost` is the IP the container binds for external communication. Inside the container network the IP would be `172.25.0.2` as shown in the error. Maybe you can try enabling external IPs  in the mysql config in the container (see [this](https://www.digitalocean.com/community/tutorials/how-to-allow-remote-access-to-mysql)).
As for linux, my guess is if above works, then the image config is somewhat different for windows.

Again I might be completely wrong :)

**Comment by knjk04** [comment]
Thanks for the link! I'll look into this

**Comment by knjk04** [comment]
Fixed with this: https://github.com/docker-library/mysql/issues/275#issuecomment-292208567

I think we need a way to access the database without using root
