### ISSUE TITLE
Find books by publisher

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#57]
Add a derived query (with JPQL) that finds all of the books by a specific publisher (the publisher passed in as an argument)

**Comment by MarcinMaruszak** [comment]
i'd like to do it

**Comment by knjk04** [comment]
Thanks!

**Comment by knjk04** [comment]
@MarcinMaruszak How are you getting on with this?

**Comment by knjk04** [comment]
@MarcinMaruszak Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by lawynnj** [comment]
Hello, can I pick this up?

**Comment by knjk04** [comment]
Hi, sure. Thanks!

**Comment by lawynnj** [comment]
@knjk04  Is the publisher (that is passed in) of type string? i.e. `findByPublisher("my_publisher")`?
