### ISSUE TITLE
Set up DGS code generation

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#63]
Add the DGS code generation build plugin and use the code generation in the data fetchers

https://netflix.github.io/dgs/generating-code-from-schema/

**Comment by kev711** [comment]
Hi @knjk04,

Can I do this ?

**Comment by knjk04** [comment]
Hi @kev711, sure. Thanks again!

**Comment by kev711** [comment]
I see there are a query type specs created in `resources\schema`. Do we need to create data fetchers on basis of query type or Repository methods in Entity Repositories ?

**Comment by knjk04** [comment]
The repository methods, please

**Comment by kev711** [comment]
I tried generating data fetchers using code generation (`generateJava` task). It seems to generate only boilerplate code with dummy methods. Rest has to be done manually.
Also, I see all but one method defined in `com.karankumar.booksapi.datafetchers.BookDataFetcher`. So I'm not sure what needs to be done here...

**Comment by knjk04** [comment]
Things like constants and the query builder for testing. See [this video](https://www.youtube.com/watch?v=oxZ6Ts9WTDM)

**Comment by knjk04** [comment]
@kev711 How are you getting on with this?

**Comment by kev711** [comment]
@knjk04 , I'm running a bit busy so I'll un assign myself from this one.

**Comment by knjk04** [comment]
@kev711 OK, thanks for letting us know
