### ISSUE TITLE
Codecov not tracking test coverage

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#65]
Our code coverage reports may not be getting sent to Codecov. Recent commits are not showing on Codecov

**Comment by Omkarganjale** [comment]
Hey, codecov is working fine. You might close this issue.

**Comment by knjk04** [comment]
![image](https://user-images.githubusercontent.com/11173328/111021665-ed6be800-83c5-11eb-94f9-d07a90abdbac.png)

Hey, it looks like it's last seeing commits from 2 months ago. Perhaps we're not sending the coverage report correctly.

https://codecov.io/gh/Project-Books/books-api

**Comment by knjk04** [comment]
--> No coverage report found.

**Comment by knjk04** [comment]
We'll be using SonarCloud to track code coverage
