### ISSUE TITLE
Find books by author

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#74]
Add a new query to find books by a particular author

**Comment by mparkersimms** [comment]
I'd like to work on this issue!

**Comment by knjk04** [comment]
@mparkersimms Thanks, I'll assign you to it! Feel free to reach out if you need a hand

**Comment by knjk04** [comment]
@mparkersimms How are you getting on with this?

**Comment by knjk04** [comment]
@mparkersimms Unassigning due to no response

**Comment by czyzu1710** [comment]
Hello! I would like to tackle this issue.

**Comment by knjk04** [comment]
@czyzu1710 Hi, thanks! I'll assign you to it

**Comment by czyzu1710** [comment]
Okay, great! If my understanding is good, it is preety much working already. But there was a problem in com.karankumar.booksapi.BooksApiApplication#populateData method and there were no rows created in book_author table. 
I changed this method a little and I'm now able to execute the query:
![image](https://user-images.githubusercontent.com/44461247/123516731-db286800-d69d-11eb-8a55-f84b22808c2d.png)
Is it the desirable output?

**Comment by knjk04** [comment]
That looks good to me

**Comment by knjk04** [comment]
@czyzu1710 How are you getting on with this?

**Comment by knjk04** [comment]
@czyzu1710 Unassigning due to no response

**Comment by maines-pet** [comment]
Hi, can I work on this issue?

**Comment by knjk04** [comment]
@maines-pet Hi, sure. Thanks!
