### ISSUE TITLE
Multiple authors saved

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#75]
In `BooksApiApplication`, we have a command line runner that prepopulates the database with some test data. Despite only creating two authors, multiple authors are created (see `SELECT * FROM author;`)

**Comment by kev711** [comment]
@knjk04 : In `application.properties` the key `spring.jpa.hibernate.ddl-auto` is set to `validate`. This setting will not remove existing data on `bootRun`. Try changing the settings to `create-drop`.

**Comment by knjk04** [comment]
Ah, thanks for this!
