### ISSUE TITLE
Create entity-relationship diagram

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#85]
Create an entity-relationship (ER) diagram for the classes in the `model/` directory.

We should show this in a new README.md file inside the `model/` directory (similar to [this](https://github.com/Project-Books/book-project/blob/0.2.0/backend/src/main/java/com/karankumar/bookproject/backend/model/README.md)).

Free software (e.g. app.diagrams.net) should be used so that we can export the file and then someone else can import it into the software again to modify it.

**Comment by himanshu007-creator** [comment]
@knjk04  sir, can you send a rough sketch of ER diag.? i will then create it

**Comment by knjk04** [comment]
You can find the entities in the [model package](https://github.com/Project-Books/books-api/tree/main/src/main/java/com/karankumar/booksapi/model). The relationships should be denoted by annotations. Hopefully that helps

**Comment by knjk04** [comment]
@himanshu007-creator How are you getting on with this?

**Comment by knjk04** [comment]
@himanshu007-creator Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by Sajal193** [comment]
Hello Sir, can I work on this issue? As I am new to this platform, I'd love to contribute myself on this. Please assign this to me.

**Comment by knjk04** [comment]
@Sajal193 Hi, sure. Thanks. Feel free to create a new GitHub discussion or reach out to use on Slack if you need any help

**Comment by Sajal193** [comment]
Dear Sir, I have sent you a message on slack. My user name is Sajal193 on
slack. I'd be happy to know from you whether the connection is
successful or not. Thank You

**Comment by knjk04** [comment]
@Sajal193 Feel free to call me Karan. Have you joined our Slack workspace (link is the Slack badge in the README)? I didn't see your username in the member list

**Comment by Sajal193** [comment]
Dear Sir,
As I have joined slack as a multi-channel guest, this channel cannot be accessed from my side. Someone alredy in the channel needs to provide me with the invitation link and only then I join the Slack workspace.

**Comment by knjk04** [comment]
Try this link: https://join.slack.com/t/teambookproject/shared_invite/zt-punc8os7-Iz9PTCAkYcO_0S~XwtO5_A

**Comment by knjk04** [comment]
@Sajal193 How are you getting on with this? I saw your comment on Slack

**Comment by Sajal193** [comment]
Yes Sir, almost done. I had a casualty in my home and so was unable to proceed with submission process. I'll be making the same very soon.

**Comment by knjk04** [comment]
@Sajal193 That's fine, no rush then. I hope everything is OK at home

**Comment by knjk04** [comment]
@Sajal193 How are you getting on with this? I know we spoke about an automated approach of generating the diagram

**Comment by Sajal193** [comment]
Yes sir, I'll be sharing my prototype shortly

**Comment by knjk04** [comment]
@Sajal193 How are you getting on?

**Comment by knjk04** [comment]
@Sajal193 Unassigning due to no response

**Comment by knjk04** [comment]
Closing as this may no longer be needed as we have some documentation through graphiql
