### ISSUE TITLE
Unable to find publisher for book

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#87]
```graphql
  "data": {
    "findAllBooks": [
      {
        "title": "Harry Potter and the Philosopher's stone",
        "authors": [],
        "publisher": null
      },
```

The `findAllBooks` query should show the publisher for the above book as 'Bloomsbury'.

Query: 
```graphql
{
   findAllBooks {
     title
     authors {
       fullName
       about
     }
     publisher {
       name
     }
    }
}
```

**Comment by maines-pet** [comment]
Hi, I would like to work on this. I've identified the issue in the book.graphqls causing this issue.

**Comment by knjk04** [comment]
Hi @maines-pet , we can assign you to this after we have merged in your work for your currently assigned issue (see contributing document)

**Comment by maines-pet** [comment]
Hi, can I now take this on?

**Comment by maines-pet** [comment]
Hi @knjk04, picking up from #125, can you please check if my approach would work on this issue?

- Change ManyToMany relationship of Book-Publisher into ManyToOne unidirectional
- Publisher_Book table will be removed as it's not needed for unidirectional Book-Publisher
- Remove the books field in Publisher class
- Update Query of BookRepository::findByPublisher to not use publisher_book join table

**Comment by knjk04** [comment]
Hi @maines-pet, apologies for the confusion, I've been thinking about this further. Let's keep the many-to-many relationship with the join table and references on both sides. We may need to update the type of publisher field in the book.graphqls schema to a list

**Comment by maines-pet** [comment]
In that case, will PR #125 be able to address the requirements now? I'm not sure if it's possible to reopen a closed PR in github.

**Comment by knjk04** [comment]
@maines-pet Yes, sorry for the mix-up. I've reopened it
