### ISSUE TITLE
Cannot drop publisher_book foreign keys

### ISSUE THREAD

**Issue by knjk04** [Project-Books/books-api#99]
**Describe the bug**
In `V010__RENAME_PUBLISHER_BOOK_CONSTRAINTS.sql`, we attempt to drop some foreign keys. However, it looks like we've already renamed them, so we need to first check whether the foreign keys with the obscure names exist.

```mysql
ALTER TABLE publisher_book
DROP FOREIGN KEY FK6buft2dj1d6ig7hekbx7c0ysp,
ADD CONSTRAINT publisher_book_publisher_id FOREIGN KEY (publisher_id) REFERENCES publisher (id);

ALTER TABLE publisher_book
DROP FOREIGN KEY FKnro4ab7u1j42osd4sehbkptrr,
ADD CONSTRAINT publisher_book_book_id FOREIGN KEY (book_id) REFERENCES book (id);

```

**To Reproduce**
1. Run the app
2. See error

**Expected behavior**
App runs without any build errors.

**Comment by lawynnj** [comment]
Just a heads up, this is blocking https://github.com/Project-Books/books-api/issues/57.

**Comment by knjk04** [comment]
@lawynnj As a temporary solution, you can remove that file

**Comment by knjk04** [comment]
This file has been removed
